package com.persistencia.seguridad.sistema;
// Generated 03/06/2017 12:49:18 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * AlbPantalla generated by hbm2java
 */
public class AlbPantalla implements java.io.Serializable {

    private Long panId;
    private AlbMenu albMenu;
    private String panNombrePantallas;
    private int panEstado;
    private String panUrl;
    private Set<PantallaPerfil> pantallaPerfils = new HashSet<PantallaPerfil>(0);
    
    public AlbPantalla() {
    }

    public AlbPantalla(AlbMenu albMenu, String panNombrePantallas, Integer panEstado) {
        this.albMenu = albMenu;
        this.panNombrePantallas = panNombrePantallas;
        this.panEstado = panEstado;
    }

    public AlbPantalla(AlbMenu albMenu, String panNombrePantallas, int panEstado, String panUrl, Set<PantallaPerfil> pantallaPerfils) {
        this.albMenu = albMenu;
        this.panNombrePantallas = panNombrePantallas;
        this.panEstado = panEstado;
        this.panUrl = panUrl;
        this.pantallaPerfils = pantallaPerfils ;

    }

    public Long getPanId() {
        return this.panId;
    }

    public void setPanId(Long panId) {
        this.panId = panId;
    }

    public AlbMenu getAlbMenu() {
        return this.albMenu;
    }

    public void setAlbMenu(AlbMenu albMenu) {
        this.albMenu = albMenu;
    }

    public String getPanNombrePantallas() {
        return this.panNombrePantallas;
    }

    public void setPanNombrePantallas(String panNombrePantallas) {
        this.panNombrePantallas = panNombrePantallas;
    }

    public int getPanEstado() {
        return panEstado;
    }

    public void setPanEstado(int panEstado) {
        this.panEstado = panEstado;
    }

    public String getPanUrl() {
        return this.panUrl;
    }

    public void setPanUrl(String panUrl) {
        this.panUrl = panUrl;
    }

    public Set<PantallaPerfil> getPantallaPerfils() {
        return pantallaPerfils;
    }

    public void setPantallaPerfils(Set<PantallaPerfil> pantallaPerfils) {
        this.pantallaPerfils = pantallaPerfils;
    }

    
}
