package com.persistencia.seguridad.sistema;
// Generated 03/06/2017 12:49:18 by Hibernate Tools 4.3.1


import com.persistencia.general.sistema.AlbRango;
import com.persistencia.general.sistema.AlbProfesion;
import com.persistencia.general.sistema.AlbEstadoCivil;
import com.persistencia.general.sistema.AlbFuerza;
import java.util.Date;

/**
 * AlbPersonalAdministrativo generated by hbm2java
 */
public class AlbPersonalAdministrativo  implements java.io.Serializable {


     private Long peaId;
     private AlbEstadoCivil albEstadoCivil;
     private AlbFuerza albFuerza;
     private AlbProfesion albProfesion;
     private AlbRango albRango;
     private Date peaFecha;
     private String peaNombres;
     private String peaApellidos;
     private Integer peaCedula;
     private Integer peaSexo;
     private String peaLugarNacimiento;
     private Date peaFechaNacimiento;
     private Integer peaCelular;
     private String peaEmail;
     private String peaObservaciones;
     private Integer peaEstado;

    public AlbPersonalAdministrativo() {
    }

    public AlbPersonalAdministrativo(AlbEstadoCivil albEstadoCivil, AlbFuerza albFuerza, AlbProfesion albProfesion, AlbRango albRango, Date peaFecha, String peaNombres, String peaApellidos, Integer peaCedula, Integer peaSexo, String peaLugarNacimiento, Date peaFechaNacimiento, Integer peaCelular, String peaEmail, String peaObservaciones, Integer peaEstado) {
       this.albEstadoCivil = albEstadoCivil;
       this.albFuerza = albFuerza;
       this.albProfesion = albProfesion;
       this.albRango = albRango;
       this.peaFecha = peaFecha;
       this.peaNombres = peaNombres;
       this.peaApellidos = peaApellidos;
       this.peaCedula = peaCedula;
       this.peaSexo = peaSexo;
       this.peaLugarNacimiento = peaLugarNacimiento;
       this.peaFechaNacimiento = peaFechaNacimiento;
       this.peaCelular = peaCelular;
       this.peaEmail = peaEmail;
       this.peaObservaciones = peaObservaciones;
       this.peaEstado = peaEstado;
    }
   
    public Long getPeaId() {
        return this.peaId;
    }
    
    public void setPeaId(Long peaId) {
        this.peaId = peaId;
    }
    public AlbEstadoCivil getAlbEstadoCivil() {
        return this.albEstadoCivil;
    }
    
    public void setAlbEstadoCivil(AlbEstadoCivil albEstadoCivil) {
        this.albEstadoCivil = albEstadoCivil;
    }
    public AlbFuerza getAlbFuerza() {
        return this.albFuerza;
    }
    
    public void setAlbFuerza(AlbFuerza albFuerza) {
        this.albFuerza = albFuerza;
    }
    public AlbProfesion getAlbProfesion() {
        return this.albProfesion;
    }
    
    public void setAlbProfesion(AlbProfesion albProfesion) {
        this.albProfesion = albProfesion;
    }
    public AlbRango getAlbRango() {
        return this.albRango;
    }
    
    public void setAlbRango(AlbRango albRango) {
        this.albRango = albRango;
    }
    public Date getPeaFecha() {
        return this.peaFecha;
    }
    
    public void setPeaFecha(Date peaFecha) {
        this.peaFecha = peaFecha;
    }
    public String getPeaNombres() {
        return this.peaNombres;
    }
    
    public void setPeaNombres(String peaNombres) {
        this.peaNombres = peaNombres;
    }
    public String getPeaApellidos() {
        return this.peaApellidos;
    }
    
    public void setPeaApellidos(String peaApellidos) {
        this.peaApellidos = peaApellidos;
    }
    public Integer getPeaCedula() {
        return this.peaCedula;
    }
    
    public void setPeaCedula(Integer peaCedula) {
        this.peaCedula = peaCedula;
    }
    public Integer getPeaSexo() {
        return this.peaSexo;
    }
    
    public void setPeaSexo(Integer peaSexo) {
        this.peaSexo = peaSexo;
    }
    public String getPeaLugarNacimiento() {
        return this.peaLugarNacimiento;
    }
    
    public void setPeaLugarNacimiento(String peaLugarNacimiento) {
        this.peaLugarNacimiento = peaLugarNacimiento;
    }
    public Date getPeaFechaNacimiento() {
        return this.peaFechaNacimiento;
    }
    
    public void setPeaFechaNacimiento(Date peaFechaNacimiento) {
        this.peaFechaNacimiento = peaFechaNacimiento;
    }
    public Integer getPeaCelular() {
        return this.peaCelular;
    }
    
    public void setPeaCelular(Integer peaCelular) {
        this.peaCelular = peaCelular;
    }
    public String getPeaEmail() {
        return this.peaEmail;
    }
    
    public void setPeaEmail(String peaEmail) {
        this.peaEmail = peaEmail;
    }
    public String getPeaObservaciones() {
        return this.peaObservaciones;
    }
    
    public void setPeaObservaciones(String peaObservaciones) {
        this.peaObservaciones = peaObservaciones;
    }
    public Integer getPeaEstado() {
        return this.peaEstado;
    }
    
    public void setPeaEstado(Integer peaEstado) {
        this.peaEstado = peaEstado;
    }




}


