package com.persistencia.seguridad.sistema;
// Generated 03/06/2017 12:49:18 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * AlbPantalla generated by hbm2java
 */
public class AlbPantalla  implements java.io.Serializable {


     private Long panId;
     private AlbMenu albMenu;
     private Integer panNombrePantallas;
     private Integer panEstado;
     private Set pantallaPerfils = new HashSet(0);

    public AlbPantalla() {
    }

    public AlbPantalla(AlbMenu albMenu, Integer panNombrePantallas, Integer panEstado, Set pantallaPerfils) {
       this.albMenu = albMenu;
       this.panNombrePantallas = panNombrePantallas;
       this.panEstado = panEstado;
       this.pantallaPerfils = pantallaPerfils;
    }
   
    public Long getPanId() {
        return this.panId;
    }
    
    public void setPanId(Long panId) {
        this.panId = panId;
    }
    public AlbMenu getAlbMenu() {
        return this.albMenu;
    }
    
    public void setAlbMenu(AlbMenu albMenu) {
        this.albMenu = albMenu;
    }
    public Integer getPanNombrePantallas() {
        return this.panNombrePantallas;
    }
    
    public void setPanNombrePantallas(Integer panNombrePantallas) {
        this.panNombrePantallas = panNombrePantallas;
    }
    public Integer getPanEstado() {
        return this.panEstado;
    }
    
    public void setPanEstado(Integer panEstado) {
        this.panEstado = panEstado;
    }
    public Set getPantallaPerfils() {
        return this.pantallaPerfils;
    }
    
    public void setPantallaPerfils(Set pantallaPerfils) {
        this.pantallaPerfils = pantallaPerfils;
    }




}


