package com.persistencia.seguridad.sistema;
// Generated 03/06/2017 12:49:18 by Hibernate Tools 4.3.1



/**
 * PantallaPerfilId generated by hbm2java
 */
public class PantallaPerfilId  implements java.io.Serializable {


     private Long perId;
     private Long panId;

    public PantallaPerfilId() {
    }

    public PantallaPerfilId(Long perId, Long panId) {
       this.perId = perId;
       this.panId = panId;
    }
   
    public Long getPerId() {
        return this.perId;
    }
    
    public void setPerId(Long perId) {
        this.perId = perId;
    }
    public Long getPanId() {
        return this.panId;
    }
    
    public void setPanId(Long panId) {
        this.panId = panId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PantallaPerfilId) ) return false;
		 PantallaPerfilId castOther = ( PantallaPerfilId ) other; 
         
		 return ( (this.getPerId()==castOther.getPerId()) || ( this.getPerId()!=null && castOther.getPerId()!=null && this.getPerId().equals(castOther.getPerId()) ) )
 && ( (this.getPanId()==castOther.getPanId()) || ( this.getPanId()!=null && castOther.getPanId()!=null && this.getPanId().equals(castOther.getPanId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getPerId() == null ? 0 : this.getPerId().hashCode() );
         result = 37 * result + ( getPanId() == null ? 0 : this.getPanId().hashCode() );
         return result;
   }   


}


