package com.persistencia.general.sistema;
// Generated 03/06/2017 12:49:18 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * AlbAvanceImplementacion generated by hbm2java
 */
public class AlbAvanceImplementacion  implements java.io.Serializable {


     private Long avaId;
     private String avaNombre;
     private Integer avaEstado;
     private Set albAlbergues = new HashSet(0);

    public AlbAvanceImplementacion() {
    }

    public AlbAvanceImplementacion(String avaNombre, Integer avaEstado, Set albAlbergues) {
       this.avaNombre = avaNombre;
       this.avaEstado = avaEstado;
       this.albAlbergues = albAlbergues;
    }
   
    public Long getAvaId() {
        return this.avaId;
    }
    
    public void setAvaId(Long avaId) {
        this.avaId = avaId;
    }
    public String getAvaNombre() {
        return this.avaNombre;
    }
    
    public void setAvaNombre(String avaNombre) {
        this.avaNombre = avaNombre;
    }
    public Integer getAvaEstado() {
        return this.avaEstado;
    }
    
    public void setAvaEstado(Integer avaEstado) {
        this.avaEstado = avaEstado;
    }
    public Set getAlbAlbergues() {
        return this.albAlbergues;
    }
    
    public void setAlbAlbergues(Set albAlbergues) {
        this.albAlbergues = albAlbergues;
    }




}


