package com.persistencia.general.sistema;
// Generated 03/06/2017 12:49:18 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * AlbCanton generated by hbm2java
 */
public class AlbCanton implements java.io.Serializable {

    private Long canId;
    private String canNombre;
    private Integer canEstado;
    private AlbProvincia albProvincia;
    private Set albAlbergues = new HashSet(0);

    public AlbCanton() {
    }

    public AlbCanton(String canNombre, Integer canEstado, Set albAlbergues) {
        this.canNombre = canNombre;
        this.canEstado = canEstado;
        this.albAlbergues = albAlbergues;
    }

    public Long getCanId() {
        return this.canId;
    }

    public void setCanId(Long canId) {
        this.canId = canId;
    }

    public String getCanNombre() {
        return this.canNombre;
    }

    public void setCanNombre(String canNombre) {
        this.canNombre = canNombre;
    }

    public Integer getCanEstado() {
        return this.canEstado;
    }

    public void setCanEstado(Integer canEstado) {
        this.canEstado = canEstado;
    }

    public Set getAlbAlbergues() {
        return this.albAlbergues;
    }

    public void setAlbAlbergues(Set albAlbergues) {
        this.albAlbergues = albAlbergues;
    }

    public AlbProvincia getAlbProvincia() {
        return albProvincia;
    }

    public void setAlbProvincia(AlbProvincia albProvincia) {
        this.albProvincia = albProvincia;
    }

    

}
