package com.persistencia.general.sistema;
// Generated 03/06/2017 12:49:18 by Hibernate Tools 4.3.1

import com.persistencia.albergue.AlbAlbergue;

/**
 * AlbCarpa generated by hbm2java
 */
public class AlbCarpa  implements java.io.Serializable {


     private Long carId;
     private AlbAlbergue albAlbergue;
     private AlbTipoCarpa albTipoCarpa;
     private Integer carTotal;
     private Integer carDisponibles;
     private Integer carEstado;

    public AlbCarpa() {
    }

    public AlbCarpa(AlbAlbergue albAlbergue, AlbTipoCarpa albTipoCarpa, Integer carTotal, Integer carDisponibles, Integer carEstado) {
       this.albAlbergue = albAlbergue;
       this.albTipoCarpa = albTipoCarpa;
       this.carTotal = carTotal;
       this.carDisponibles = carDisponibles;
       this.carEstado = carEstado;
    }
   
    public Long getCarId() {
        return this.carId;
    }
    
    public void setCarId(Long carId) {
        this.carId = carId;
    }
    public AlbAlbergue getAlbAlbergue() {
        return this.albAlbergue;
    }
    
    public void setAlbAlbergue(AlbAlbergue albAlbergue) {
        this.albAlbergue = albAlbergue;
    }
    public AlbTipoCarpa getAlbTipoCarpa() {
        return this.albTipoCarpa;
    }
    
    public void setAlbTipoCarpa(AlbTipoCarpa albTipoCarpa) {
        this.albTipoCarpa = albTipoCarpa;
    }
    public Integer getCarTotal() {
        return this.carTotal;
    }
    
    public void setCarTotal(Integer carTotal) {
        this.carTotal = carTotal;
    }
    public Integer getCarDisponibles() {
        return this.carDisponibles;
    }
    
    public void setCarDisponibles(Integer carDisponibles) {
        this.carDisponibles = carDisponibles;
    }
    public Integer getCarEstado() {
        return this.carEstado;
    }
    
    public void setCarEstado(Integer carEstado) {
        this.carEstado = carEstado;
    }




}


