package com.persistencia.general.sistema;
// Generated 03/06/2017 12:49:18 by Hibernate Tools 4.3.1



/**
 * AlbEmpresa generated by hbm2java
 */
public class AlbEmpresa  implements java.io.Serializable {


     private Long empId;
     private AlbTipoEmpresa albTipoEmpresa;
     private String empNombre;
     private Integer empEstado;

    public AlbEmpresa() {
    }

    public AlbEmpresa(AlbTipoEmpresa albTipoEmpresa, String empNombre, Integer empEstado) {
       this.albTipoEmpresa = albTipoEmpresa;
       this.empNombre = empNombre;
       this.empEstado = empEstado;
    }
   
    public Long getEmpId() {
        return this.empId;
    }
    
    public void setEmpId(Long empId) {
        this.empId = empId;
    }
    public AlbTipoEmpresa getAlbTipoEmpresa() {
        return this.albTipoEmpresa;
    }
    
    public void setAlbTipoEmpresa(AlbTipoEmpresa albTipoEmpresa) {
        this.albTipoEmpresa = albTipoEmpresa;
    }
    public String getEmpNombre() {
        return this.empNombre;
    }
    
    public void setEmpNombre(String empNombre) {
        this.empNombre = empNombre;
    }
    public Integer getEmpEstado() {
        return this.empEstado;
    }
    
    public void setEmpEstado(Integer empEstado) {
        this.empEstado = empEstado;
    }




}


