package com.persistencia.general.sistema;
// Generated 03/06/2017 12:49:18 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * AlbEstadoCivil generated by hbm2java
 */
public class AlbEstadoCivil  implements java.io.Serializable {


     private Long eciId;
     private String eciTipo;
     private Integer eciEstado;
     private Set albDamnificados = new HashSet(0);
     private Set albPersonalAdministrativos = new HashSet(0);

    public AlbEstadoCivil() {
    }

    public AlbEstadoCivil(String eciTipo, Integer eciEstado, Set albDamnificados, Set albPersonalAdministrativos) {
       this.eciTipo = eciTipo;
       this.eciEstado = eciEstado;
       this.albDamnificados = albDamnificados;
       this.albPersonalAdministrativos = albPersonalAdministrativos;
    }
   
    public Long getEciId() {
        return this.eciId;
    }
    
    public void setEciId(Long eciId) {
        this.eciId = eciId;
    }
    public String getEciTipo() {
        return this.eciTipo;
    }
    
    public void setEciTipo(String eciTipo) {
        this.eciTipo = eciTipo;
    }
    public Integer getEciEstado() {
        return this.eciEstado;
    }
    
    public void setEciEstado(Integer eciEstado) {
        this.eciEstado = eciEstado;
    }
    public Set getAlbDamnificados() {
        return this.albDamnificados;
    }
    
    public void setAlbDamnificados(Set albDamnificados) {
        this.albDamnificados = albDamnificados;
    }
    public Set getAlbPersonalAdministrativos() {
        return this.albPersonalAdministrativos;
    }
    
    public void setAlbPersonalAdministrativos(Set albPersonalAdministrativos) {
        this.albPersonalAdministrativos = albPersonalAdministrativos;
    }




}


