package com.persistencia.general.sistema;
// Generated 03/06/2017 12:49:18 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * AlbFuerza generated by hbm2java
 */
public class AlbFuerza  implements java.io.Serializable {


     private Long fueId;
     private String fueFuerza;
     private Integer fueEstado;
     private Set albPersonalAdministrativos = new HashSet(0);

    public AlbFuerza() {
    }

    public AlbFuerza(String fueFuerza, Integer fueEstado, Set albPersonalAdministrativos) {
       this.fueFuerza = fueFuerza;
       this.fueEstado = fueEstado;
       this.albPersonalAdministrativos = albPersonalAdministrativos;
    }
   
    public Long getFueId() {
        return this.fueId;
    }
    
    public void setFueId(Long fueId) {
        this.fueId = fueId;
    }
    public String getFueFuerza() {
        return this.fueFuerza;
    }
    
    public void setFueFuerza(String fueFuerza) {
        this.fueFuerza = fueFuerza;
    }
    public Integer getFueEstado() {
        return this.fueEstado;
    }
    
    public void setFueEstado(Integer fueEstado) {
        this.fueEstado = fueEstado;
    }
    public Set getAlbPersonalAdministrativos() {
        return this.albPersonalAdministrativos;
    }
    
    public void setAlbPersonalAdministrativos(Set albPersonalAdministrativos) {
        this.albPersonalAdministrativos = albPersonalAdministrativos;
    }




}


