package com.persistencia.general.sistema;
// Generated 03/06/2017 12:49:18 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * AlbInstruccion generated by hbm2java
 */
public class AlbInstruccion  implements java.io.Serializable {


     private Long insId;
     private String insNombre;
     private Integer insEstado;
     private Set albDamnificados = new HashSet(0);

    public AlbInstruccion() {
    }

    public AlbInstruccion(String insNombre, Integer insEstado, Set albDamnificados) {
       this.insNombre = insNombre;
       this.insEstado = insEstado;
       this.albDamnificados = albDamnificados;
    }
   
    public Long getInsId() {
        return this.insId;
    }
    
    public void setInsId(Long insId) {
        this.insId = insId;
    }
    public String getInsNombre() {
        return this.insNombre;
    }
    
    public void setInsNombre(String insNombre) {
        this.insNombre = insNombre;
    }
    public Integer getInsEstado() {
        return this.insEstado;
    }
    
    public void setInsEstado(Integer insEstado) {
        this.insEstado = insEstado;
    }
    public Set getAlbDamnificados() {
        return this.albDamnificados;
    }
    
    public void setAlbDamnificados(Set albDamnificados) {
        this.albDamnificados = albDamnificados;
    }




}


