package com.persistencia.general.sistema;
// Generated 03/06/2017 12:49:18 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * AlbProfesion generated by hbm2java
 */
public class AlbProfesion  implements java.io.Serializable {


     private Long prfId;
     private String prfProfesion;
     private Integer prfEstado;
     private Set albDamnificados = new HashSet(0);
     private Set albPersonalAdministrativos = new HashSet(0);

    public AlbProfesion() {
    }

    public AlbProfesion(String prfProfesion, Integer prfEstado, Set albDamnificados, Set albPersonalAdministrativos) {
       this.prfProfesion = prfProfesion;
       this.prfEstado = prfEstado;
       this.albDamnificados = albDamnificados;
       this.albPersonalAdministrativos = albPersonalAdministrativos;
    }
   
    public Long getPrfId() {
        return this.prfId;
    }
    
    public void setPrfId(Long prfId) {
        this.prfId = prfId;
    }
    public String getPrfProfesion() {
        return this.prfProfesion;
    }
    
    public void setPrfProfesion(String prfProfesion) {
        this.prfProfesion = prfProfesion;
    }
    public Integer getPrfEstado() {
        return this.prfEstado;
    }
    
    public void setPrfEstado(Integer prfEstado) {
        this.prfEstado = prfEstado;
    }
    public Set getAlbDamnificados() {
        return this.albDamnificados;
    }
    
    public void setAlbDamnificados(Set albDamnificados) {
        this.albDamnificados = albDamnificados;
    }
    public Set getAlbPersonalAdministrativos() {
        return this.albPersonalAdministrativos;
    }
    
    public void setAlbPersonalAdministrativos(Set albPersonalAdministrativos) {
        this.albPersonalAdministrativos = albPersonalAdministrativos;
    }




}


