package com.persistencia.general.sistema;
// Generated 03/06/2017 12:49:18 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * AlbParteDiario generated by hbm2java
 */
public class AlbParteDiario  implements java.io.Serializable {


     private Long padId;
     private Date padFecha;
     private Date padFechaIncidencia;
     private Integer padMilitDisponibles;
     private Integer padMilitLicencia;
     private Integer padMilitPermiso;
     private Integer padMilitDescansoOp;
     private Integer padMilitSeguridad;
     private Integer padAdultos;
     private Integer padAdolescentes;
     private Integer padNinos;
     private Integer padAncianos;
     private Integer padDiscapacitados;
     private String padObservaciones;
     private Integer padEstado;
     private Set partediarioAlbergues = new HashSet(0);

    public AlbParteDiario() {
    }

    public AlbParteDiario(Date padFecha, Date padFechaIncidencia, Integer padMilitDisponibles, Integer padMilitLicencia, Integer padMilitPermiso, Integer padMilitDescansoOp, Integer padMilitSeguridad, Integer padAdultos, Integer padAdolescentes, Integer padNinos, Integer padAncianos, Integer padDiscapacitados, String padObservaciones, Integer padEstado, Set partediarioAlbergues) {
       this.padFecha = padFecha;
       this.padFechaIncidencia = padFechaIncidencia;
       this.padMilitDisponibles = padMilitDisponibles;
       this.padMilitLicencia = padMilitLicencia;
       this.padMilitPermiso = padMilitPermiso;
       this.padMilitDescansoOp = padMilitDescansoOp;
       this.padMilitSeguridad = padMilitSeguridad;
       this.padAdultos = padAdultos;
       this.padAdolescentes = padAdolescentes;
       this.padNinos = padNinos;
       this.padAncianos = padAncianos;
       this.padDiscapacitados = padDiscapacitados;
       this.padObservaciones = padObservaciones;
       this.padEstado = padEstado;
       this.partediarioAlbergues = partediarioAlbergues;
    }
   
    public Long getPadId() {
        return this.padId;
    }
    
    public void setPadId(Long padId) {
        this.padId = padId;
    }
    public Date getPadFecha() {
        return this.padFecha;
    }
    
    public void setPadFecha(Date padFecha) {
        this.padFecha = padFecha;
    }
    public Date getPadFechaIncidencia() {
        return this.padFechaIncidencia;
    }
    
    public void setPadFechaIncidencia(Date padFechaIncidencia) {
        this.padFechaIncidencia = padFechaIncidencia;
    }
    public Integer getPadMilitDisponibles() {
        return this.padMilitDisponibles;
    }
    
    public void setPadMilitDisponibles(Integer padMilitDisponibles) {
        this.padMilitDisponibles = padMilitDisponibles;
    }
    public Integer getPadMilitLicencia() {
        return this.padMilitLicencia;
    }
    
    public void setPadMilitLicencia(Integer padMilitLicencia) {
        this.padMilitLicencia = padMilitLicencia;
    }
    public Integer getPadMilitPermiso() {
        return this.padMilitPermiso;
    }
    
    public void setPadMilitPermiso(Integer padMilitPermiso) {
        this.padMilitPermiso = padMilitPermiso;
    }
    public Integer getPadMilitDescansoOp() {
        return this.padMilitDescansoOp;
    }
    
    public void setPadMilitDescansoOp(Integer padMilitDescansoOp) {
        this.padMilitDescansoOp = padMilitDescansoOp;
    }
    public Integer getPadMilitSeguridad() {
        return this.padMilitSeguridad;
    }
    
    public void setPadMilitSeguridad(Integer padMilitSeguridad) {
        this.padMilitSeguridad = padMilitSeguridad;
    }
    public Integer getPadAdultos() {
        return this.padAdultos;
    }
    
    public void setPadAdultos(Integer padAdultos) {
        this.padAdultos = padAdultos;
    }
    public Integer getPadAdolescentes() {
        return this.padAdolescentes;
    }
    
    public void setPadAdolescentes(Integer padAdolescentes) {
        this.padAdolescentes = padAdolescentes;
    }
    public Integer getPadNinos() {
        return this.padNinos;
    }
    
    public void setPadNinos(Integer padNinos) {
        this.padNinos = padNinos;
    }
    public Integer getPadAncianos() {
        return this.padAncianos;
    }
    
    public void setPadAncianos(Integer padAncianos) {
        this.padAncianos = padAncianos;
    }
    public Integer getPadDiscapacitados() {
        return this.padDiscapacitados;
    }
    
    public void setPadDiscapacitados(Integer padDiscapacitados) {
        this.padDiscapacitados = padDiscapacitados;
    }
    public String getPadObservaciones() {
        return this.padObservaciones;
    }
    
    public void setPadObservaciones(String padObservaciones) {
        this.padObservaciones = padObservaciones;
    }
    public Integer getPadEstado() {
        return this.padEstado;
    }
    
    public void setPadEstado(Integer padEstado) {
        this.padEstado = padEstado;
    }
    public Set getPartediarioAlbergues() {
        return this.partediarioAlbergues;
    }
    
    public void setPartediarioAlbergues(Set partediarioAlbergues) {
        this.partediarioAlbergues = partediarioAlbergues;
    }




}


