package com.persistencia.general.sistema;
// Generated 03/06/2017 12:49:18 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * AlbAvanceImplementacion generated by hbm2java
 */
public class AlbTipoAlbergue implements java.io.Serializable {


     private Long tiaId;
     private String tiaNombre;
     private Integer tiaEstado;
     private Set albAlbergues = new HashSet(0);

    public AlbTipoAlbergue() {
    }

    public AlbTipoAlbergue(String tiaNombre, Integer tiaEstado, Set albAlbergues) {
       this.tiaNombre = tiaNombre;
       this.tiaEstado = tiaEstado;
       this.albAlbergues = albAlbergues;
    }

    public Long getTiaId() {
        return tiaId;
    }

    public void setTiaId(Long tiaId) {
        this.tiaId = tiaId;
    }

    public String getTiaNombre() {
        return tiaNombre;
    }

    public void setTiaNombre(String tiaNombre) {
        this.tiaNombre = tiaNombre;
    }

    public Integer getTiaEstado() {
        return tiaEstado;
    }

    public void setTiaEstado(Integer tiaEstado) {
        this.tiaEstado = tiaEstado;
    }
   
    
    public Set getAlbAlbergues() {
        return this.albAlbergues;
    }
    
    public void setAlbAlbergues(Set albAlbergues) {
        this.albAlbergues = albAlbergues;
    }




}


