package com.persistencia.general.sistema;
// Generated 03/06/2017 12:49:18 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * AlbTipoCarpa generated by hbm2java
 */
public class AlbTipoCarpa  implements java.io.Serializable {


     private Long ticId;
     private String ticNombre;
     private Integer ticEstado;
     private Set albCarpas = new HashSet(0);

    public AlbTipoCarpa() {
    }

    public AlbTipoCarpa(String ticNombre, Integer ticEstado, Set albCarpas) {
       this.ticNombre = ticNombre;
       this.ticEstado = ticEstado;
       this.albCarpas = albCarpas;
    }
   
    public Long getTicId() {
        return this.ticId;
    }
    
    public void setTicId(Long ticId) {
        this.ticId = ticId;
    }
    public String getTicNombre() {
        return this.ticNombre;
    }
    
    public void setTicNombre(String ticNombre) {
        this.ticNombre = ticNombre;
    }
    public Integer getTicEstado() {
        return this.ticEstado;
    }
    
    public void setTicEstado(Integer ticEstado) {
        this.ticEstado = ticEstado;
    }
    public Set getAlbCarpas() {
        return this.albCarpas;
    }
    
    public void setAlbCarpas(Set albCarpas) {
        this.albCarpas = albCarpas;
    }




}


