package com.persistencia.general.sistema;
// Generated 03/06/2017 12:49:18 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * AlbTipoVehiculo generated by hbm2java
 */
public class AlbTipoVehiculo  implements java.io.Serializable {


     private Long tivId;
     private String tivNombre;
     private Integer tivEstado;
     private Set albVehiculos = new HashSet(0);

    public AlbTipoVehiculo() {
    }

    public AlbTipoVehiculo(String tivNombre, Integer tivEstado, Set albVehiculos) {
       this.tivNombre = tivNombre;
       this.tivEstado = tivEstado;
       this.albVehiculos = albVehiculos;
    }
   
    public Long getTivId() {
        return this.tivId;
    }
    
    public void setTivId(Long tivId) {
        this.tivId = tivId;
    }
    public String getTivNombre() {
        return this.tivNombre;
    }
    
    public void setTivNombre(String tivNombre) {
        this.tivNombre = tivNombre;
    }
    public Integer getTivEstado() {
        return this.tivEstado;
    }
    
    public void setTivEstado(Integer tivEstado) {
        this.tivEstado = tivEstado;
    }
    public Set getAlbVehiculos() {
        return this.albVehiculos;
    }
    
    public void setAlbVehiculos(Set albVehiculos) {
        this.albVehiculos = albVehiculos;
    }




}


