package com.persistencia.general.sistema;
// Generated 03/06/2017 12:49:18 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * AlbTipoEmpresa generated by hbm2java
 */
public class AlbTipoEmpresa  implements java.io.Serializable {


     private Long tieId;
     private String tieNombre;
     private Integer tieEstado;
     private Set albEmpresas = new HashSet(0);

    public AlbTipoEmpresa() {
    }

    public AlbTipoEmpresa(String tieNombre, Integer tieEstado, Set albEmpresas) {
       this.tieNombre = tieNombre;
       this.tieEstado = tieEstado;
       this.albEmpresas = albEmpresas;
    }
   
    public Long getTieId() {
        return this.tieId;
    }
    
    public void setTieId(Long tieId) {
        this.tieId = tieId;
    }
    public String getTieNombre() {
        return this.tieNombre;
    }
    
    public void setTieNombre(String tieNombre) {
        this.tieNombre = tieNombre;
    }
    public Integer getTieEstado() {
        return this.tieEstado;
    }
    
    public void setTieEstado(Integer tieEstado) {
        this.tieEstado = tieEstado;
    }
    public Set getAlbEmpresas() {
        return this.albEmpresas;
    }
    
    public void setAlbEmpresas(Set albEmpresas) {
        this.albEmpresas = albEmpresas;
    }




}


