package com.persistencia.general.sistema;
// Generated 03/06/2017 12:49:18 by Hibernate Tools 4.3.1

import com.persistencia.damnificado.AlbDamnificado;

/**
 * DamnificadoDiscapacidad generated by hbm2java
 */
public class DamnificadoDiscapacidad  implements java.io.Serializable {


     private DamnificadoDiscapacidadId id;
     private AlbDamnificado albDamnificado;
     private AlbDiscapacidad albDiscapacidad;

    public DamnificadoDiscapacidad() {
    }

	
    public DamnificadoDiscapacidad(DamnificadoDiscapacidadId id) {
        this.id = id;
    }
    public DamnificadoDiscapacidad(DamnificadoDiscapacidadId id, AlbDamnificado albDamnificado, AlbDiscapacidad albDiscapacidad) {
       this.id = id;
       this.albDamnificado = albDamnificado;
       this.albDiscapacidad = albDiscapacidad;
    }
   
    public DamnificadoDiscapacidadId getId() {
        return this.id;
    }
    
    public void setId(DamnificadoDiscapacidadId id) {
        this.id = id;
    }
    public AlbDamnificado getAlbDamnificado() {
        return this.albDamnificado;
    }
    
    public void setAlbDamnificado(AlbDamnificado albDamnificado) {
        this.albDamnificado = albDamnificado;
    }
    public AlbDiscapacidad getAlbDiscapacidad() {
        return this.albDiscapacidad;
    }
    
    public void setAlbDiscapacidad(AlbDiscapacidad albDiscapacidad) {
        this.albDiscapacidad = albDiscapacidad;
    }




}


