package com.persistencia.general.sistema;
// Generated 03/06/2017 12:49:18 by Hibernate Tools 4.3.1



/**
 * DamnificadoDiscapacidadId generated by hbm2java
 */
public class DamnificadoDiscapacidadId  implements java.io.Serializable {


     private Long damId;
     private Long disId;

    public DamnificadoDiscapacidadId() {
    }

    public DamnificadoDiscapacidadId(Long damId, Long disId) {
       this.damId = damId;
       this.disId = disId;
    }
   
    public Long getDamId() {
        return this.damId;
    }
    
    public void setDamId(Long damId) {
        this.damId = damId;
    }
    public Long getDisId() {
        return this.disId;
    }
    
    public void setDisId(Long disId) {
        this.disId = disId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DamnificadoDiscapacidadId) ) return false;
		 DamnificadoDiscapacidadId castOther = ( DamnificadoDiscapacidadId ) other; 
         
		 return ( (this.getDamId()==castOther.getDamId()) || ( this.getDamId()!=null && castOther.getDamId()!=null && this.getDamId().equals(castOther.getDamId()) ) )
 && ( (this.getDisId()==castOther.getDisId()) || ( this.getDisId()!=null && castOther.getDisId()!=null && this.getDisId().equals(castOther.getDisId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getDamId() == null ? 0 : this.getDamId().hashCode() );
         result = 37 * result + ( getDisId() == null ? 0 : this.getDisId().hashCode() );
         return result;
   }   


}


