package com.persistencia.albergue;
// Generated 03/06/2017 12:49:18 by Hibernate Tools 4.3.1



/**
 * DamnificadoAlbergueId generated by hbm2java
 */
public class DamnificadoAlbergueId  implements java.io.Serializable {


     private Long damId;
     private Long albId;

    public DamnificadoAlbergueId() {
    }

    public DamnificadoAlbergueId(Long damId, Long albId) {
       this.damId = damId;
       this.albId = albId;
    }
   
    public Long getDamId() {
        return this.damId;
    }
    
    public void setDamId(Long damId) {
        this.damId = damId;
    }
    public Long getAlbId() {
        return this.albId;
    }
    
    public void setAlbId(Long albId) {
        this.albId = albId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DamnificadoAlbergueId) ) return false;
		 DamnificadoAlbergueId castOther = ( DamnificadoAlbergueId ) other; 
         
		 return ( (this.getDamId()==castOther.getDamId()) || ( this.getDamId()!=null && castOther.getDamId()!=null && this.getDamId().equals(castOther.getDamId()) ) )
 && ( (this.getAlbId()==castOther.getAlbId()) || ( this.getAlbId()!=null && castOther.getAlbId()!=null && this.getAlbId().equals(castOther.getAlbId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getDamId() == null ? 0 : this.getDamId().hashCode() );
         result = 37 * result + ( getAlbId() == null ? 0 : this.getAlbId().hashCode() );
         return result;
   }   


}


