package com.persistencia.albergue;
// Generated 03/06/2017 12:49:18 by Hibernate Tools 4.3.1

import com.persistencia.damnificado.AlbDamnificado;

/**
 * DamnificadoAlbergue generated by hbm2java
 */
public class DamnificadoAlbergue  implements java.io.Serializable {


     private DamnificadoAlbergueId id;
     private AlbAlbergue albAlbergue;
     private AlbDamnificado albDamnificado;

    public DamnificadoAlbergue() {
    }

	
    public DamnificadoAlbergue(DamnificadoAlbergueId id) {
        this.id = id;
    }
    public DamnificadoAlbergue(DamnificadoAlbergueId id, AlbAlbergue albAlbergue, AlbDamnificado albDamnificado) {
       this.id = id;
       this.albAlbergue = albAlbergue;
       this.albDamnificado = albDamnificado;
    }
   
    public DamnificadoAlbergueId getId() {
        return this.id;
    }
    
    public void setId(DamnificadoAlbergueId id) {
        this.id = id;
    }
    public AlbAlbergue getAlbAlbergue() {
        return this.albAlbergue;
    }
    
    public void setAlbAlbergue(AlbAlbergue albAlbergue) {
        this.albAlbergue = albAlbergue;
    }
    public AlbDamnificado getAlbDamnificado() {
        return this.albDamnificado;
    }
    
    public void setAlbDamnificado(AlbDamnificado albDamnificado) {
        this.albDamnificado = albDamnificado;
    }




}


