package com.persistencia.albergue;
// Generated 03/06/2017 12:49:18 by Hibernate Tools 4.3.1



/**
 * PartediarioAlbergueId generated by hbm2java
 */
public class PartediarioAlbergueId  implements java.io.Serializable {


     private Long padId;
     private Long albId;

    public PartediarioAlbergueId() {
    }

    public PartediarioAlbergueId(Long padId, Long albId) {
       this.padId = padId;
       this.albId = albId;
    }
   
    public Long getPadId() {
        return this.padId;
    }
    
    public void setPadId(Long padId) {
        this.padId = padId;
    }
    public Long getAlbId() {
        return this.albId;
    }
    
    public void setAlbId(Long albId) {
        this.albId = albId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PartediarioAlbergueId) ) return false;
		 PartediarioAlbergueId castOther = ( PartediarioAlbergueId ) other; 
         
		 return ( (this.getPadId()==castOther.getPadId()) || ( this.getPadId()!=null && castOther.getPadId()!=null && this.getPadId().equals(castOther.getPadId()) ) )
 && ( (this.getAlbId()==castOther.getAlbId()) || ( this.getAlbId()!=null && castOther.getAlbId()!=null && this.getAlbId().equals(castOther.getAlbId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getPadId() == null ? 0 : this.getPadId().hashCode() );
         result = 37 * result + ( getAlbId() == null ? 0 : this.getAlbId().hashCode() );
         return result;
   }   


}


