package com.persistencia.albergue;
// Generated 03/06/2017 12:49:18 by Hibernate Tools 4.3.1

import com.persistencia.general.sistema.AlbParteDiario;
import com.persistencia.general.sistema.AlbParteDiario;




/**
 * PartediarioAlbergue generated by hbm2java
 */
public class PartediarioAlbergue  implements java.io.Serializable {


     private PartediarioAlbergueId id;
     private AlbAlbergue albAlbergue;
     private AlbParteDiario albParteDiario;

    public PartediarioAlbergue() {
    }

	
    public PartediarioAlbergue(PartediarioAlbergueId id) {
        this.id = id;
    }
    public PartediarioAlbergue(PartediarioAlbergueId id, AlbAlbergue albAlbergue, AlbParteDiario albParteDiario) {
       this.id = id;
       this.albAlbergue = albAlbergue;
       this.albParteDiario = albParteDiario;
    }
   
    public PartediarioAlbergueId getId() {
        return this.id;
    }
    
    public void setId(PartediarioAlbergueId id) {
        this.id = id;
    }
    public AlbAlbergue getAlbAlbergue() {
        return this.albAlbergue;
    }
    
    public void setAlbAlbergue(AlbAlbergue albAlbergue) {
        this.albAlbergue = albAlbergue;
    }
    public AlbParteDiario getAlbParteDiario() {
        return this.albParteDiario;
    }
    
    public void setAlbParteDiario(AlbParteDiario albParteDiario) {
        this.albParteDiario = albParteDiario;
    }




}


