package com.persistencia.albergue;
// Generated 03/06/2017 12:49:18 by Hibernate Tools 4.3.1


import com.persistencia.albergue.servicio.AlbServicio;
import java.util.HashSet;
import java.util.Set;

/**
 * ServicioSituacionAlbergue generated by hbm2java
 */
public class ServicioSituacionAlbergue  implements java.io.Serializable {


     private Long serAlbId;
     private AlbAlbergue albAlbergue;
     private AlbServicio albServicio;
     private Set albSituacions = new HashSet(0);

    public ServicioSituacionAlbergue() {
    }

    public ServicioSituacionAlbergue(AlbAlbergue albAlbergue, AlbServicio albServicio, Set albSituacions) {
       this.albAlbergue = albAlbergue;
       this.albServicio = albServicio;
       this.albSituacions = albSituacions;
    }
   
    public Long getSerAlbId() {
        return this.serAlbId;
    }
    
    public void setSerAlbId(Long serAlbId) {
        this.serAlbId = serAlbId;
    }
    public AlbAlbergue getAlbAlbergue() {
        return this.albAlbergue;
    }
    
    public void setAlbAlbergue(AlbAlbergue albAlbergue) {
        this.albAlbergue = albAlbergue;
    }
    public AlbServicio getAlbServicio() {
        return this.albServicio;
    }
    
    public void setAlbServicio(AlbServicio albServicio) {
        this.albServicio = albServicio;
    }
    public Set getAlbSituacions() {
        return this.albSituacions;
    }
    
    public void setAlbSituacions(Set albSituacions) {
        this.albSituacions = albSituacions;
    }




}


